services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    restart: unless-stopped

  flask-app:
    build: .
    container_name: flask-app
    ports:
      - "5000:5000"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434 # important!! not localhost but service name
    depends_on:
      - ollama
    restart: unless-stopped

volumes:
  ollama_data: